### ISSUE TITLE
model.solve() on linux 

### ISSUE THREAD

**Issue by ion-g-ion** [calculix/pygccx#5]
Calling model.solve() on Linux (Ubuntu 22.04) returns `FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ccx -i "holder"'` emerging from the `subprocess.run()` call from model.py. 
Adding the argument `subprocess.run(..., shell=True)` solves the issue for me.

BR, 
Ion

**Comment by FrozenWinterheart** [comment]
Hi Ion,
Unfortunately i can't test under linux, so i need some help from you.
shell = True should be avoided where ever it can, because it may introduce security issues.

I think i have found a solution. The reason is, linux and windows interpret the args in subprocess.run differently if passed as a string. They should be passed as a list.
subprocess.run([self.ccx_path, '-i', self.jobname], cwd=self.working_dir, env=env)
works for me unter windows. Can you give it a try?

BR,
Matthias

**Comment by ion-g-ion** [comment]
Hi Matthias,

I tried passing the arguments as a list as you suggested and it works fine.

BR,
Ion

**Comment by FrozenWinterheart** [comment]
Hi Ion,
thank you for your help! The fix will be in my next commit to main branch.

BR,
Matthias

**Comment by soylentOrange** [comment]
I had a similar issue with model.solve() on my mac (Apple M1 Max running 15.0.1 (24A348), Calculix installed via conda). 
Unfortunately, the solution above didn't work.

As a workaround, I replaced the call to model.solve() in my user code with:

```
# create env for the subsequent call to subprocess
env = os.environ
env['OMP_NUM_THREADS'] = f'{ccx_no_cpu}'

# using call to subprocess instead of model.solve()
subprocess.run([model.ccx_path, "-i", model.jobname], cwd=model.working_dir, env=env) 

```
Best regard and thanks for your great work,
Robert

**Comment by FrozenWinterheart** [comment]
Hello Robert, 
thank you for your feedback!
If i compare your code with my current code, the only difference is, that you use the os.envion object and not a simple dict.

I have tested your code under windows and it works. I will include it in the next release.

Thank you and best regards,
Matthias
